apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: bell
  POSTGRES_USER: bell
  POSTGRES_PASSWORD: bell
  PGDATA: /var/lib/postgresql/data/mydata